// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_MLO37JyU_Ev50PrwGRkdNtcPOe10fE',
    appId: '1:588222641037:web:7ccd61411d6e379414c3c4',
    messagingSenderId: '588222641037',
    projectId: 'bus-management-c8612',
    authDomain: 'bus-management-c8612.firebaseapp.com',
    databaseURL: 'https://bus-management-c8612-default-rtdb.firebaseio.com',
    storageBucket: 'bus-management-c8612.firebasestorage.app',
    measurementId: 'G-ZWXRLXTED9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3OwN3zYs_Bz3fPUUCThqowLaiyjOJN8',
    appId: '1:588222641037:android:677bf40875a12ad614c3c4',
    messagingSenderId: '588222641037',
    projectId: 'bus-management-c8612',
    databaseURL: 'https://bus-management-c8612-default-rtdb.firebaseio.com',
    storageBucket: 'bus-management-c8612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChYY9uqyBc9JCf8jSOsMtTlUxOukFah9Y',
    appId: '1:588222641037:ios:fb25939adaa20bbe14c3c4',
    messagingSenderId: '588222641037',
    projectId: 'bus-management-c8612',
    databaseURL: 'https://bus-management-c8612-default-rtdb.firebaseio.com',
    storageBucket: 'bus-management-c8612.firebasestorage.app',
    iosBundleId: 'com.example.trackgoStudentParent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChYY9uqyBc9JCf8jSOsMtTlUxOukFah9Y',
    appId: '1:588222641037:ios:fb25939adaa20bbe14c3c4',
    messagingSenderId: '588222641037',
    projectId: 'bus-management-c8612',
    databaseURL: 'https://bus-management-c8612-default-rtdb.firebaseio.com',
    storageBucket: 'bus-management-c8612.firebasestorage.app',
    iosBundleId: 'com.example.trackgoStudentParent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw_MLO37JyU_Ev50PrwGRkdNtcPOe10fE',
    appId: '1:588222641037:web:3e2fd81fdf810f6414c3c4',
    messagingSenderId: '588222641037',
    projectId: 'bus-management-c8612',
    authDomain: 'bus-management-c8612.firebaseapp.com',
    databaseURL: 'https://bus-management-c8612-default-rtdb.firebaseio.com',
    storageBucket: 'bus-management-c8612.firebasestorage.app',
    measurementId: 'G-GC77WBMTTE',
  );
}
